### Dataset #1: Olympic Medalists

This dataset is taken from Wikipedia's table of Summer Olympic medalists, available at this [link](https://en.wikipedia.org/wiki/Lists_of_Olympic_medalists). The first challenge I ran into was figuring out the best way to get the data from the table on Wikipedia. I didn’t want to dive too deep into other Python packages or libraries since we’re mostly focusing on **pandas** right now. I tried the **pandas** built-in function `read_html()`, but I received an HTTP 403 error. I searched for a workaround and found that some people had success using the **requests** library, but I wasn’t able to get `read_html()` to properly parse the text of the request object. I eventually took a manual approach and copied the table directly into Excel, then saved it as a CSV for easier use. I think **BeautifulSoup** would be helpful here, but since it looks like we’ll cover that later, I wanted to stay within the scope of this project.

In [7]:
import pandas as pd


medalists_untidy = pd.read_csv("Summer Olympic Medalists CSV.csv")

medalists_untidy.head(10)

,Discipline (link to medalists list),Contested,Number of,Unnamed: 3,Medals awarded,Unnamed: 5,Unnamed: 6,Unnamed: 7,Athlete(s) with the most medals,Athlete(s) with the most gold medals
0,NaN,NaN,Olympics,Medal events,"1st place, gold medalist(s)","2nd place, silver medalist(s)","3rd place, bronze medalist(s)",Total,(gold–silver–bronze),NaN
1,NaN,NaN,(up to conclusion of 2024),(in 2024),NaN,NaN,NaN,NaN,NaN,NaN
2,Archery,1900–1908; 1920; since 1972,18,5,76,74,66,216,Hubert van Innis (BEL) (6–3–0),Hubert van Innis (BEL) (6–3–0)
3,Artistic swimming,Since 1984,11,2,22,20,21,63,Svetlana Romashina (RUS) (7–0–0),Svetlana Romashina (RUS) (7–0–0)
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Huang Xuechen (CHN) (0–5–2),NaN
5,Athletics,Since 1896,30,48,1075,1084,1073,3232,Paavo Nurmi (FIN) (9–3–0),Paavo Nurmi (FIN) (9–3–0)
6,"(men, women)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carl Lewis (USA) (9–1–0)
7,Badminton,Since 1992,9,5,44,44,48,136,Gao Ling (CHN) (2–1–1),Gao Ling (CHN) (2–1–1)
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fu Haifeng (CHN) (2–1–0)
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Viktor Axelsen (DEN) (2–0–1)

Very messy. Let's start with building a list of what we want our column names to be. Then,

In [ ]:
columns = ['Discipline', 'Contested', 'Number of Olympics', 'Medal Events', '# of Gold MedalsP']